### ISSUE TITLE
Reporte practica architech Yael Santiago

### ISSUE THREAD

**Issue by YaelStO** [SistemasTecTlaxiaco/actividad-3-practica-architect-YaelStO#1]
[Reporte de Practica_Yael de Jesus Santiago Ortiz.pdf](https://github.com/SistemasTecTlaxiaco/actividad-3-practica-architect-YaelStO/files/12554002/Reporte.de.Practica_Yael.de.Jesus.Santiago.Ortiz.pdf)
[](url)

**Comment by YaelStO** [comment]
[Reporte de Practica_Yael de Jesus Santiago Ortiz.pdf](https://github.com/SistemasTecTlaxiaco/actividad-3-practica-architect-YaelStO/files/12554000/Reporte.de.Practica_Yael.de.Jesus.Santiago.Ortiz.pdf)

**Comment by luzm23** [comment]
19/20

**Comment by luzm23** [comment]
18/20

**Comment by josealfredo79** [comment]
Favor de complementar bien los trabajos..lista de figuras...numerado de las figuras...procedimiento....
